### ISSUE TITLE
code generation tracking issue

### ISSUE THREAD

**Issue by felixangell** [felixangell/krug#15]
* [x] if statements
* [ ] else if
* [ ] else
* [ ] while loops
* [ ] loops
* [ ] function calls (no arguments)
* [ ] function calls (arguments)
* [ ] global variables
* [x] local variables
* [ ] function return statement
* [ ] function return with expression
* [ ] breaking out of loops
* [ ] skipping iteration in loop
* [ ] block evaluation with eval
* [ ] lambdas
* [ ] array indexing
* [ ] allocating arrays
* [ ] unary expressions
* [x] binary expressions
* [ ] pointers
* [ ] address of
