### ISSUE TITLE
x86-64 instruction encoding todo list

### ISSUE THREAD

**Issue by felixangell** [felixangell/krug#59]
These are the instructions that need to be encoded so that I can switch the current backend to use the x64 encoder/obj writer over the current method:

* [ ] mov_val_reg
* [ ] add_val_reg
* [ ] sub_val_reg
* [ ] je
* [ ] jne
* [ ] jmp
* [ ] cmp
* [ ] set_val
* [ ] lea
* [ ] call

###### Resources:
* [osdev](https://wiki.osdev.org/X86-64_Instruction_Encoding)
* [intel manual, chapter 2](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf)
* [coder64](http://ref.x86asm.net/coder64.html)
