### ISSUE TITLE
codegen tracking issue

### ISSUE THREAD

**Issue by felixangell** [felixangell/krug#96]
for the llvm backend

* [ ] else if
* [x] for loop
* [x] infinite loop
* [x] if statement
* [x] while loops
* [ ] defer (handled in ir?)
* [ ] global variables
* [x] local variables
* [x] variable access
* [x] variable re-assignment
* [ ] next
* [x] return?
* [ ] eval block/yield
* [ ] floating point types
* [x] address of
* [x] arithmetic
    - [x] signed
    - [ ] unsigned
* [x] modulo operator
* [x] division op
* [x] add and sub
* [x] shift left/right
* [x] bitwise and, or, xor, not
* [ ] type casting
* [ ] anonymous functions
* [ ] match
* [ ] structure types
   - [x] structure type default values
   - [ ] packed attribute
* [x] array types
* [ ] tagged union
* [ ] enums
* [ ] type promotion?
* [x] pointers
* [x] address of
* [ ] methods?
* [ ] path expressions
* [ ] slices?
* [ ] tuples
* [x] structure field access
* [ ] boolean operators
* [ ]
